name: build-and-placement
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Add permission to gradlew
        run: chmod +x gradlew

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle and execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jsBrowserProductionWebpack

      - name: Copy build artifacts to /docs directory
        run: |
          cp -fRT ./build/distributions ./docs

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated GitHub Pages contents
          file_pattern: ./docs/*
