name: build-and-placement
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Add permission to gradlew
        run: chmod +x gradlew

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle and execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jsBrowserProductionWebpack

      - name: Copy build artifacts to /docs directory
        run: |
          cp -f -r ./build/distributions ./docs

      - name: Setup Git config
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config pull.rebase false

      - name: Commit and push
        run: |
          git add -f ./docs
          git commit -m "Updated GitHub Pages contents"
          git pull origin master
          git push origin master
